server.port=9092
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.username=${SYSTEM_EMAIL_ID}
spring.mail.password=${SYSTEM_EMAIL_PASSWORD}
